# Default values for xl-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
ImageRepository: "xebialabs/xl-deploy"
ImageTag: "8.5.0"
ImagePullPolicy: "Always"
# ImagePullSecret: xlDeploy

ingress:
  Enabled: true
  annotations:
    # ingress.kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - example.com
  tls:
   - secretName: example-secretsName
     hosts:
       - example.com

xldDevelopmentMode: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

volumes:
  ## ERROR: Using /usr/local/* results in this error,
  ## Warning  FailedMount  3s (x6 over 19s)  kubelet, MountVolume.SetUp failed for volume "xld-bootstrap" : mkdir /usr/local/xld-bootstrap: read-only file system
  ## Warning  FailedMount  3s (x6 over 19s)  kubelet, MountVolume.SetUp failed for volume "xld-data" : mkdir /usr/local/xld-data: read-only file system
  ## By passed by changing /usr to /tmp, this fails with EULA agreement error.
  - name: xld-bootstrap
    hostPath:
      path: /usr/local/xld-bootstrap
      type: DirectoryOrCreate
  - name: xld-data
    hostPath:
      path: /usr/local/xld-data
      type: DirectoryOrCreate

HealthProbes: true
HealthProbesLivenessTimeout: 60
HealthProbesReadinessTimeout: 60
HealthProbeFailureThreshold: 12
HealthPeriodScans: 10

nodeSelector: {}

tolerations: []

affinity: {}

Persistence:
  Enabled: false
  ## Choose storage class provided by your cloud provider, example "ssd" on GKE, AWS and OpenStack
  # StorageClass: "-"
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 10Gi
