apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xl-deploy.fullname" . }}
  labels:
    app: {{ template "xl-deploy.name" . }}
    chart: {{ template "xl-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "xl-deploy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "xl-deploy.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ImageRepository }}:{{ .Values.ImageTag }}"
          imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
          ports:
            - name: xld-http
              containerPort: 4516
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/xl-deploy/xld-bootstrap
              name: xld-bootstrap
            - mountPath: /opt/xl-deploy/xld-data
              name: xld-data
  {{- if .Values.HealthProbes }}
          livenessProbe:
            httpGet:
              path: /
              port: xld-http
            initialDelaySeconds: {{ .Values.HealthProbesLivenessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: xld-http
            initialDelaySeconds: {{ .Values.HealthProbesReadinessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
{{- end }}
          env:
            - name: XLD_DEVELOPMENT_MODE
              value: "{{ .Values.xldDevelopmentMode }}"
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
