{{- if and .Values.Persistence.Enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.Persistence.Annotations }}
  annotations:
{{ toYaml .Values.Persistence.Annotations | indent 4 }}
{{- end }}
  name: {{ template "xl-deploy.fullname" . }}
  labels:
    app: {{ template "xl-deploy.name" . }}
    chart: {{ template "xl-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.Persistence.AccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.Persistence.Size | quote }}
{{- if .Values.Persistence.StorageClass }}
{{- if (eq "-" .Values.Persistence.StorageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.Persistence.StorageClass }}"
{{- end }}
{{- end }}
{{- end }}
