apiVersion: v1
kind: Service
metadata:
  name: {{ template "xl-deploy.fullname" . }}
  labels:
    app: {{ template "xl-deploy.name" . }}
    chart: {{ template "xl-deploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: xld-http
      protocol: TCP
      name: xld-http-svc
  selector:
    app: {{ template "xl-deploy.name" . }}
    release: {{ .Release.Name }}
